#Server properties
spring.application.name=ems
server.port=8090

#JDBC properties
#spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent

spring.datasource.url=jdbc:mysql://root:sJHiTcOHyzIWeIQeeAhWOftndXtyWJnf@thomas.proxy.rlwy.net:13033/railway
spring.datasource.username=root
spring.datasource.password=sJHiTcOHyzIWeIQeeAhWOftndXtyWJnf

# Allow frontend domain (CORS)
allowed.origins=https://emsclient.netlify.app/


#Console stuff
spring.main.banner-mode=off

#security stuff
logging.level.org.springframework.security=DEBUG

#swagger ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

